class Country {
  static String getPhoneCountryCode(String iso) {
    String code;
    countryMap.asMap().forEach((key, value) {
      if (iso == value['iso_code']) {
        code = value['phone_code'].toString();
      }
    });
    return code;
  }

  static List<Map> countryMap = [
    {
      "id": 1,
      "name": "Afghanistan",
      "phone_code": 93,
      "currency": "AFN",
      "iso_code": "AF",
    },
    {
      "id": 2,
      "name": "Albania",
      "phone_code": 355,
      "currency": "ALL",
      "iso_code": "AL",
    },
    {
      "id": 3,
      "name": "Algeria",
      "phone_code": 213,
      "currency": "DZD",
      "iso_code": "DZ",
    },
    {
      "id": 4,
      "name": "American Samoa",
      "phone_code": 1,
      "currency": "USD",
      "iso_code": "AS",
    },
    {
      "id": 5,
      "name": "Andorra",
      "phone_code": 376,
      "currency": "EUR",
      "iso_code": "AD",
    },
    {
      "id": 6,
      "name": "Angola",
      "phone_code": 244,
      "currency": "AOA",
      "iso_code": "AO",
    },
    {
      "id": 7,
      "name": "Anguilla",
      "phone_code": 1,
      "currency": "XCD",
      "iso_code": "AI",
    },
    {
      "id": 8,
      "name": "Antarctica",
      "phone_code": 672,
      "currency": "USD",
      "iso_code": "AQ",
    },
    {
      "id": 9,
      "name": "Antigua and Barbuda",
      "phone_code": 1,
      "currency": "XCD",
      "iso_code": "AG",
    },
    {
      "id": 10,
      "name": "Argentina",
      "phone_code": 54,
      "currency": "ARS",
      "iso_code": "AR",
    },
    {
      "id": 11,
      "name": "Armenia",
      "phone_code": 374,
      "currency": "AMD",
      "iso_code": "AM",
    },
    {
      "id": 12,
      "name": "Aruba",
      "phone_code": 297,
      "currency": "AWG",
      "iso_code": "AW",
    },
    {
      "id": 13,
      "name": "Australia",
      "phone_code": 61,
      "currency": "AUD",
      "iso_code": "AU",
    },
    {
      "id": 14,
      "name": "Austria",
      "phone_code": 43,
      "currency": "EUR",
      "iso_code": "AT",
    },
    {
      "id": 15,
      "name": "Azerbaijan",
      "phone_code": 994,
      "currency": "AZN",
      "iso_code": "AZ",
    },
    {
      "id": 16,
      "name": "Bahamas",
      "phone_code": 1,
      "currency": "BSD",
      "iso_code": "BS",
    },
    {
      "id": 17,
      "name": "Bahrain",
      "phone_code": 973,
      "currency": "BHD",
      "iso_code": "BH",
    },
    {
      "id": 18,
      "name": "Bangladesh",
      "phone_code": 880,
      "currency": "BDT",
      "iso_code": "BD",
    },
    {
      "id": 19,
      "name": "Barbados",
      "phone_code": 1,
      "currency": "BBD",
      "iso_code": "BB",
    },
    {
      "id": 20,
      "name": "Belarus",
      "phone_code": 375,
      "currency": "BYN",
      "iso_code": "BY",
    },
    {
      "id": 21,
      "name": "Belgium",
      "phone_code": 32,
      "currency": "EUR",
      "iso_code": "BE",
    },
    {
      "id": 22,
      "name": "Belize",
      "phone_code": 501,
      "currency": "BZD",
      "iso_code": "BZ",
    },
    {
      "id": 23,
      "name": "Benin",
      "phone_code": 229,
      "currency": "XOF",
      "iso_code": "BJ",
    },
    {
      "id": 24,
      "name": "Bermuda",
      "phone_code": 1,
      "currency": "USD",
      "iso_code": "BM",
    },
    {
      "id": 25,
      "name": "Bhutan",
      "phone_code": 975,
      "currency": "BTN",
      "iso_code": "BT",
    },
    {
      "id": 26,
      "name": "Bolivia",
      "phone_code": 591,
      "currency": "BOB",
      "iso_code": "BO",
    },
    {
      "id": 27,
      "name": "Bosnia and Herzegovina",
      "phone_code": 387,
      "currency": "BAM",
      "iso_code": "BA",
    },
    {
      "id": 28,
      "name": "Botswana",
      "phone_code": 267,
      "currency": "BWP",
      "iso_code": "BW",
    },
    {
      "id": 29,
      "name": "Brazil",
      "phone_code": 55,
      "currency": "BRL",
      "iso_code": "BR",
    },
    {
      "id": 30,
      "name": "British Virgin Islands",
      "phone_code": 1,
      "currency": "USD",
      "iso_code": "VG",
    },
    {
      "id": 31,
      "name": "Brunei",
      "phone_code": 673,
      "currency": "BND",
      "iso_code": "BN",
    },
    {
      "id": 32,
      "name": "Bulgaria",
      "phone_code": 359,
      "currency": "BGN",
      "iso_code": "BG",
    },
    {
      "id": 33,
      "name": "Burkina Faso",
      "phone_code": 226,
      "currency": "XOF",
      "iso_code": "BF",
    },
    {
      "id": 34,
      "name": "Burundi",
      "phone_code": 257,
      "currency": "BIF",
      "iso_code": "BI",
    },
    {
      "id": 35,
      "name": "Cambodia",
      "phone_code": 855,
      "currency": "KHR",
      "iso_code": "KH",
    },
    {
      "id": 36,
      "name": "Cameroon",
      "phone_code": 237,
      "currency": "XAF",
      "iso_code": "CM",
    },
    {
      "id": 37,
      "name": "Canada",
      "phone_code": 1,
      "currency": "CAD",
      "iso_code": "CA",
    },
    {
      "id": 38,
      "name": "Cape Verde",
      "phone_code": 238,
      "currency": "CVE",
      "iso_code": "CV",
    },
    {
      "id": 39,
      "name": "Cayman Islands",
      "phone_code": 1,
      "currency": "KYD",
      "iso_code": "KY",
    },
    {
      "id": 40,
      "name": "Central African Republic",
      "phone_code": 236,
      "currency": "XAF",
      "iso_code": "CF",
    },
    {
      "id": 41,
      "name": "Chad",
      "phone_code": 235,
      "currency": "XAF",
      "iso_code": "TD",
    },
    {
      "id": 42,
      "name": "Chile",
      "phone_code": 56,
      "currency": "CLP",
      "iso_code": "CL",
    },
    {
      "id": 43,
      "name": "China",
      "phone_code": 86,
      "currency": "CNY",
      "iso_code": "CN",
    },
    {
      "id": 44,
      "name": "Christmas Island",
      "phone_code": 61,
      "currency": "AUD",
      "iso_code": "CX",
    },
    {
      "id": 45,
      "name": "Cocos (Keeling) Islands",
      "phone_code": 61,
      "currency": "AUD",
      "iso_code": "CC",
    },
    {
      "id": 46,
      "name": "Colombia",
      "phone_code": 57,
      "currency": "COP",
      "iso_code": "CO",
    },
    {
      "id": 47,
      "name": "Comoros",
      "phone_code": 269,
      "currency": "KMF",
      "iso_code": "KM",
    },
    {
      "id": 48,
      "name": "Congo, Democratic Republic of the",
      "phone_code": 243,
      "currency": "XAF",
      "iso_code": "CD",
    },
    {
      "id": 49,
      "name": "Congo, Republic of the",
      "phone_code": 242,
      "currency": "XAF",
      "iso_code": "CG",
    },
    {
      "id": 50,
      "name": "Cook Islands",
      "phone_code": 682,
      "currency": "NZD",
      "iso_code": "CK",
    },
    {
      "id": 51,
      "name": "Costa Rica",
      "phone_code": 506,
      "currency": "CRC",
      "iso_code": "CR",
    },
    {
      "id": 52,
      "name": "Croatia",
      "phone_code": 385,
      "currency": "HRK",
      "iso_code": "HR",
    },
    {
      "id": 53,
      "name": "Cuba",
      "phone_code": 53,
      "currency": "CUC",
      "iso_code": "CU",
    },
    {
      "id": 54,
      "name": "Cyprus",
      "phone_code": 357,
      "currency": "EUR",
      "iso_code": "CY",
    },
    {
      "id": 55,
      "name": "Czech Republic",
      "phone_code": 420,
      "currency": "CZK",
      "iso_code": "CZ",
    },
    {
      "id": 56,
      "name": "Denmark",
      "phone_code": 45,
      "currency": "DKK",
      "iso_code": "DK",
    },
    {
      "id": 57,
      "name": "Djibouti",
      "phone_code": 253,
      "currency": "DJF",
      "iso_code": "DJ",
    },
    {
      "id": 58,
      "name": "Dominica",
      "phone_code": 1,
      "currency": "XCD",
      "iso_code": "DM",
    },
    {
      "id": 59,
      "name": "Dominican Republic",
      "phone_code": 1,
      "currency": "DOP",
      "iso_code": "DO",
    },
    {
      "id": 60,
      "name": "Ecuador",
      "phone_code": 593,
      "currency": "USD",
      "iso_code": "EC",
    },
    {
      "id": 61,
      "name": "Egypt",
      "phone_code": 20,
      "currency": "EGP",
      "iso_code": "EG",
    },
    {
      "id": 62,
      "name": "El Salvador",
      "phone_code": 503,
      "currency": "SVC",
      "iso_code": "SV",
    },
    {
      "id": 63,
      "name": "Equatorial Guinea",
      "phone_code": 240,
      "currency": "XAF",
      "iso_code": "GQ",
    },
    {
      "id": 64,
      "name": "Eritrea",
      "phone_code": 291,
      "currency": "ERN",
      "iso_code": "ER",
    },
    {
      "id": 65,
      "name": "Estonia",
      "phone_code": 372,
      "currency": "EUR",
      "iso_code": "EE",
    },
    {
      "id": 66,
      "name": "Ethiopia",
      "phone_code": 251,
      "currency": "ETB",
      "iso_code": "ET",
    },
    {
      "id": 67,
      "name": "Falkland Islands",
      "phone_code": 500,
      "currency": "USD",
      "iso_code": "FK",
    },
    {
      "id": 68,
      "name": "Faroe Islands",
      "phone_code": 298,
      "currency": "DKK",
      "iso_code": "FO",
    },
    {
      "id": 69,
      "name": "Fiji",
      "phone_code": 679,
      "currency": "FJD",
      "iso_code": "FJ",
    },
    {
      "id": 70,
      "name": "Finland",
      "phone_code": 358,
      "currency": "EUR",
      "iso_code": "FI",
    },
    {
      "id": 71,
      "name": "France",
      "phone_code": 33,
      "currency": "EUR",
      "iso_code": "FR",
    },
    {
      "id": 72,
      "name": "French Polynesia",
      "phone_code": 689,
      "currency": "XPF",
      "iso_code": "PF",
    },
    {
      "id": 73,
      "name": "Gabon",
      "phone_code": 241,
      "currency": "XAF",
      "iso_code": "GA",
    },
    {
      "id": 74,
      "name": "Gambia, The",
      "phone_code": 220,
      "currency": "GMD",
      "iso_code": "GM",
    },
    {
      "id": 75,
      "name": "Georgia",
      "phone_code": 995,
      "currency": "GEL",
      "iso_code": "GE",
    },
    {
      "id": 76,
      "name": "Germany",
      "phone_code": 49,
      "currency": "EUR",
      "iso_code": "DE",
    },
    {
      "id": 77,
      "name": "Ghana",
      "phone_code": 233,
      "currency": "GHS",
      "iso_code": "GH",
    },
    {
      "id": 78,
      "name": "Gibraltar",
      "phone_code": 350,
      "currency": "GIP",
      "iso_code": "GI",
    },
    {
      "id": 79,
      "name": "Greece",
      "phone_code": 30,
      "currency": "EUR",
      "iso_code": "GR",
    },
    {
      "id": 80,
      "name": "Greenland",
      "phone_code": 299,
      "currency": "USD",
      "iso_code": "GL",
    },
    {
      "id": 81,
      "name": "Grenada",
      "phone_code": 1,
      "currency": "XCD",
      "iso_code": "GD",
    },
    {
      "id": 82,
      "name": "Guam",
      "phone_code": 1,
      "currency": "USD",
      "iso_code": "GU",
    },
    {
      "id": 83,
      "name": "Guatemala",
      "phone_code": 502,
      "currency": "GTQ",
      "iso_code": "GT",
    },
    {
      "id": 84,
      "name": "Guinea",
      "phone_code": 224,
      "currency": "GNF",
      "iso_code": "GN",
    },
    {
      "id": 85,
      "name": "Guinea-Bissau",
      "phone_code": 245,
      "currency": "XAF",
      "iso_code": "GW",
    },
    {
      "id": 86,
      "name": "Guyana",
      "phone_code": 592,
      "currency": "GYD",
      "iso_code": "GY",
    },
    {
      "id": 87,
      "name": "Haiti",
      "phone_code": 509,
      "currency": "HTG",
      "iso_code": "HT",
    },
    {
      "id": 88,
      "name": "Holy See (Vatican City)",
      "phone_code": 39,
      "currency": "EUR",
      "iso_code": "VA",
    },
    {
      "id": 89,
      "name": "Honduras",
      "phone_code": 504,
      "currency": "HNL",
      "iso_code": "HN",
    },
    {
      "id": 90,
      "name": "Hong Kong",
      "phone_code": 852,
      "currency": "HKD",
      "iso_code": "HK",
    },
    {
      "id": 91,
      "name": "Hungary",
      "phone_code": 36,
      "currency": "HUF",
      "iso_code": "HU",
    },
    {
      "id": 92,
      "name": "Iceland",
      "phone_code": 354,
      "currency": "ISK",
      "iso_code": "IS",
    },
    {
      "id": 93,
      "name": "India",
      "phone_code": 91,
      "currency": "INR",
      "iso_code": "IN",
    },
    {
      "id": 94,
      "name": "Indonesia",
      "phone_code": 62,
      "currency": "IDR",
      "iso_code": "ID",
    },
    {
      "id": 95,
      "name": "Iran",
      "phone_code": 98,
      "currency": "IRR",
      "iso_code": "IR",
    },
    {
      "id": 96,
      "name": "Iraq",
      "phone_code": 964,
      "currency": "IQD",
      "iso_code": "IQ",
    },
    {
      "id": 97,
      "name": "Ireland",
      "phone_code": 353,
      "currency": "EUR",
      "iso_code": "IE",
    },
    {
      "id": 98,
      "name": "Isle of Man",
      "phone_code": 44,
      "currency": "USD",
      "iso_code": "IM",
    },
    {
      "id": 99,
      "name": "Israel",
      "phone_code": 972,
      "currency": "ILS",
      "iso_code": "IL",
    },
    {
      "id": 100,
      "name": "Italy",
      "phone_code": 39,
      "currency": "EUR",
      "iso_code": "IT",
    },
    {
      "id": 101,
      "name": "Ivory Coast",
      "phone_code": 225,
      "currency": "XOF",
      "iso_code": "CI",
    },
    {
      "id": 102,
      "name": "Jamaica",
      "phone_code": 1,
      "currency": "JMD",
      "iso_code": "JM",
    },
    {
      "id": 103,
      "name": "Japan",
      "phone_code": 81,
      "currency": "JPY",
      "iso_code": "JP",
    },
    {
      "id": 104,
      "name": "Jordan",
      "phone_code": 962,
      "currency": "JOD",
      "iso_code": "JO",
    },
    {
      "id": 105,
      "name": "Kazakhstan",
      "phone_code": 7,
      "currency": "KZT",
      "iso_code": "KZ",
    },
    {
      "id": 106,
      "name": "Kenya",
      "phone_code": 254,
      "currency": "KES",
      "iso_code": "KE",
    },
    {
      "id": 107,
      "name": "Kiribati",
      "phone_code": 686,
      "currency": "AUD",
      "iso_code": "KI",
    },
    {
      "id": 108,
      "name": "Korea, North",
      "phone_code": 850,
      "currency": "KPW",
      "iso_code": "KP",
    },
    {
      "id": 109,
      "name": "Korea, South",
      "phone_code": 82,
      "currency": "KRW",
      "iso_code": "KR",
    },
    {
      "id": 110,
      "name": "Kuwait",
      "phone_code": 965,
      "currency": "KWD",
      "iso_code": "KW",
    },
    {
      "id": 111,
      "name": "Kyrgyzstan",
      "phone_code": 996,
      "currency": "EUR",
      "iso_code": "KG",
    },
    {
      "id": 112,
      "name": "Laos",
      "phone_code": 856,
      "currency": "LAK",
      "iso_code": "LA",
    },
    {
      "id": 113,
      "name": "Latvia",
      "phone_code": 371,
      "currency": "EUR",
      "iso_code": "LV",
    },
    {
      "id": 114,
      "name": "Lebanon",
      "phone_code": 961,
      "currency": "LBP",
      "iso_code": "LB",
    },
    {
      "id": 115,
      "name": "Lesotho",
      "phone_code": 266,
      "currency": "LSL",
      "iso_code": "LS",
    },
    {
      "id": 116,
      "name": "Liberia",
      "phone_code": 231,
      "currency": "LRD",
      "iso_code": "LR",
    },
    {
      "id": 117,
      "name": "Libya",
      "phone_code": 218,
      "currency": "LYD",
      "iso_code": "LY",
    },
    {
      "id": 118,
      "name": "Liechtenstein",
      "phone_code": 423,
      "currency": "CHF",
      "iso_code": "LI",
    },
    {
      "id": 119,
      "name": "Lithuania",
      "phone_code": 370,
      "currency": "LTL",
      "iso_code": "LT",
    },
    {
      "id": 120,
      "name": "Luxembourg",
      "phone_code": 352,
      "currency": "EUR",
      "iso_code": "LU",
    },
    {
      "id": 121,
      "name": "Macau",
      "phone_code": 853,
      "currency": "MOP",
      "iso_code": "MO",
    },
    {
      "id": 122,
      "name": "Macedonia",
      "phone_code": 389,
      "currency": "MKD",
      "iso_code": "MK",
    },
    {
      "id": 123,
      "name": "Madagascar",
      "phone_code": 261,
      "currency": "MGA",
      "iso_code": "MG",
    },
    {
      "id": 124,
      "name": "Malawi",
      "phone_code": 265,
      "currency": "MWK",
      "iso_code": "MW",
    },
    {
      "id": 125,
      "name": "Malaysia",
      "phone_code": 60,
      "currency": "MYR",
      "iso_code": "MY",
    },
    {
      "id": 126,
      "name": "Maldives",
      "phone_code": 960,
      "currency": "MVR",
      "iso_code": "MV",
    },
    {
      "id": 127,
      "name": "Mali",
      "phone_code": 223,
      "currency": "XOF",
      "iso_code": "ML",
    },
    {
      "id": 128,
      "name": "Malta",
      "phone_code": 356,
      "currency": "EUR",
      "iso_code": "MT",
    },
    {
      "id": 129,
      "name": "Marshall Islands",
      "phone_code": 692,
      "currency": "USD",
      "iso_code": "MH",
    },
    {
      "id": 130,
      "name": "Mauritania",
      "phone_code": 222,
      "currency": "MRO",
      "iso_code": "MR",
    },
    {
      "id": 131,
      "name": "Mauritius",
      "phone_code": 230,
      "currency": "MUR",
      "iso_code": "MU",
    },
    {
      "id": 132,
      "name": "Mayotte",
      "phone_code": 262,
      "currency": "EUR",
      "iso_code": "YT",
    },
    {
      "id": 133,
      "name": "Mexico",
      "phone_code": 52,
      "currency": "MXN",
      "iso_code": "MX",
    },
    {
      "id": 134,
      "name": "Micronesia, Federated States of",
      "phone_code": 691,
      "currency": "USD",
      "iso_code": "FM",
    },
    {
      "id": 135,
      "name": "Moldova",
      "phone_code": 373,
      "currency": "MDL",
      "iso_code": "MD",
    },
    {
      "id": 136,
      "name": "Monaco",
      "phone_code": 377,
      "currency": "EUR",
      "iso_code": "MC",
    },
    {
      "id": 137,
      "name": "Mongolia",
      "phone_code": 976,
      "currency": "MNT",
      "iso_code": "MN",
    },
    {
      "id": 138,
      "name": "Montenegro",
      "phone_code": 382,
      "currency": "EUR",
      "iso_code": "ME",
    },
    {
      "id": 139,
      "name": "Montserrat",
      "phone_code": 1,
      "currency": "XCD",
      "iso_code": "MS",
    },
    {
      "id": 140,
      "name": "Morocco",
      "phone_code": 212,
      "currency": "MAD",
      "iso_code": "MA",
    },
    {
      "id": 141,
      "name": "Mozambique",
      "phone_code": 258,
      "currency": "MZN",
      "iso_code": "MZ",
    },
    {
      "id": 142,
      "name": "Namibia",
      "phone_code": 264,
      "currency": "NAD",
      "iso_code": "NA",
    },
    {
      "id": 143,
      "name": "Nauru",
      "phone_code": 674,
      "currency": "AUD",
      "iso_code": "NR",
    },
    {
      "id": 144,
      "name": "Nepal",
      "phone_code": 977,
      "currency": "NPR",
      "iso_code": "NP",
    },
    {
      "id": 145,
      "name": "Netherlands",
      "phone_code": 31,
      "currency": "EUR",
      "iso_code": "NL",
    },
    {
      "id": 146,
      "name": "Netherlands Antilles",
      "phone_code": 599,
      "currency": "USD",
      "iso_code": "AN",
    },
    {
      "id": 147,
      "name": "New Caledonia",
      "phone_code": 687,
      "currency": "XPF",
      "iso_code": "NC",
    },
    {
      "id": 148,
      "name": "New Zealand",
      "phone_code": 64,
      "currency": "NZD",
      "iso_code": "NZ",
    },
    {
      "id": 149,
      "name": "Nicaragua",
      "phone_code": 505,
      "currency": "NIO",
      "iso_code": "NI",
    },
    {
      "id": 150,
      "name": "Niger",
      "phone_code": 227,
      "currency": "XOF",
      "iso_code": "NE",
    },
    {
      "id": 151,
      "name": "Nigeria",
      "phone_code": 234,
      "currency": "NGN",
      "iso_code": "NG",
    },
    {
      "id": 152,
      "name": "Niue",
      "phone_code": 683,
      "currency": "NZD",
      "iso_code": "NU",
    },
    {
      "id": 153,
      "name": "Northern Mariana Islands",
      "phone_code": 1,
      "currency": "USD",
      "iso_code": "MP",
    },
    {
      "id": 154,
      "name": "Norway",
      "phone_code": 47,
      "currency": "NOK",
      "iso_code": "NO",
    },
    {
      "id": 155,
      "name": "Oman",
      "phone_code": 968,
      "currency": "OMR",
      "iso_code": "OM",
    },
    {
      "id": 156,
      "name": "Pakistan",
      "phone_code": 92,
      "currency": "PKR",
      "iso_code": "PK",
    },
    {
      "id": 157,
      "name": "Palau",
      "phone_code": 680,
      "currency": "USD",
      "iso_code": "PW",
    },
    {
      "id": 158,
      "name": "Panama",
      "phone_code": 507,
      "currency": "PAB",
      "iso_code": "PA",
    },
    {
      "id": 159,
      "name": "Papua New Guinea",
      "phone_code": 675,
      "currency": "PGK",
      "iso_code": "PG",
    },
    {
      "id": 160,
      "name": "Paraguay",
      "phone_code": 595,
      "currency": "PYG",
      "iso_code": "PY",
    },
    {
      "id": 161,
      "name": "Peru",
      "phone_code": 51,
      "currency": "PEN",
      "iso_code": "PE",
    },
    {
      "id": 162,
      "name": "Philippines",
      "phone_code": 63,
      "currency": "PHP",
      "iso_code": "PH",
    },
    {
      "id": 163,
      "name": "Pitcairn Islands",
      "phone_code": 870,
      "currency": "USD",
      "iso_code": "PN",
    },
    {
      "id": 164,
      "name": "Poland",
      "phone_code": 48,
      "currency": "PLN",
      "iso_code": "PL",
    },
    {
      "id": 165,
      "name": "Portugal",
      "phone_code": 351,
      "currency": "EUR",
      "iso_code": "PT",
    },
    {
      "id": 166,
      "name": "Puerto Rico",
      "phone_code": 1,
      "currency": "USD",
      "iso_code": "PR",
    },
    {
      "id": 167,
      "name": "Qatar",
      "phone_code": 974,
      "currency": "QAR",
      "iso_code": "QA",
    },
    {
      "id": 168,
      "name": "Romania",
      "phone_code": 40,
      "currency": "RON",
      "iso_code": "RO",
    },
    {
      "id": 169,
      "name": "Russia",
      "phone_code": 7,
      "currency": "RUB",
      "iso_code": "RU",
    },
    {
      "id": 170,
      "name": "Rwanda",
      "phone_code": 250,
      "currency": "RWF",
      "iso_code": "RW",
    },
    {
      "id": 171,
      "name": "Saint Helena",
      "phone_code": 290,
      "currency": "USD",
      "iso_code": "SH",
    },
    {
      "id": 172,
      "name": "Saint Kitts and Nevis",
      "phone_code": 1,
      "currency": "USD",
      "iso_code": "KN",
    },
    {
      "id": 173,
      "name": "Saint Lucia",
      "phone_code": 1,
      "currency": "XCD",
      "iso_code": "LC",
    },
    {
      "id": 174,
      "name": "Saint Pierre and Miquelon",
      "phone_code": 508,
      "currency": "EUR",
      "iso_code": "PM",
    },
    {
      "id": 175,
      "name": "Saint Vincent and the Grenadines",
      "phone_code": 1,
      "currency": "USD",
      "iso_code": "VC",
    },
    {
      "id": 176,
      "name": "Samoa",
      "phone_code": 685,
      "currency": "USD",
      "iso_code": "WS",
    },
    {
      "id": 177,
      "name": "San Marino",
      "phone_code": 378,
      "currency": "EUR",
      "iso_code": "SM",
    },
    {
      "id": 178,
      "name": "Sao Tome and Principe",
      "phone_code": 239,
      "currency": "USD",
      "iso_code": "ST",
    },
    {
      "id": 179,
      "name": "Saudi Arabia",
      "phone_code": 966,
      "currency": "SAR",
      "iso_code": "SA",
    },
    {
      "id": 180,
      "name": "Senegal",
      "phone_code": 221,
      "currency": "XOF",
      "iso_code": "SN",
    },
    {
      "id": 181,
      "name": "Serbia",
      "phone_code": 381,
      "currency": "RSD",
      "iso_code": "RS",
    },
    {
      "id": 182,
      "name": "Seychelles",
      "phone_code": 248,
      "currency": "SCR",
      "iso_code": "SC",
    },
    {
      "id": 183,
      "name": "Sierra Leone",
      "phone_code": 232,
      "currency": "SLL",
      "iso_code": "SL",
    },
    {
      "id": 184,
      "name": "Singapore",
      "phone_code": 65,
      "currency": "SGD",
      "iso_code": "SG",
    },
    {
      "id": 185,
      "name": "Slovakia",
      "phone_code": 421,
      "currency": "EUR",
      "iso_code": "SK",
    },
    {
      "id": 186,
      "name": "Slovenia",
      "phone_code": 386,
      "currency": "EUR",
      "iso_code": "SI",
    },
    {
      "id": 187,
      "name": "Solomon Islands",
      "phone_code": 677,
      "currency": "SBD",
      "iso_code": "SB",
    },
    {
      "id": 188,
      "name": "Somalia",
      "phone_code": 252,
      "currency": "SOS",
      "iso_code": "SO",
    },
    {
      "id": 189,
      "name": "South Africa",
      "phone_code": 27,
      "currency": "ZAR",
      "iso_code": "ZA",
    },
    {
      "id": 190,
      "name": "Spain",
      "phone_code": 34,
      "currency": "EUR",
      "iso_code": "ES",
    },
    {
      "id": 191,
      "name": "Sri Lanka",
      "phone_code": 94,
      "currency": "LKR",
      "iso_code": "LK",
    },
    {
      "id": 192,
      "name": "Sudan",
      "phone_code": 249,
      "currency": "SDG",
      "iso_code": "SD",
    },
    {
      "id": 193,
      "name": "Suriname",
      "phone_code": 597,
      "currency": "SRD",
      "iso_code": "SR",
    },
    {
      "id": 194,
      "name": "Swaziland",
      "phone_code": 268,
      "currency": "SZL",
      "iso_code": "SZ",
    },
    {
      "id": 195,
      "name": "Sweden",
      "phone_code": 46,
      "currency": "SEK",
      "iso_code": "SE",
    },
    {
      "id": 196,
      "name": "Switzerland",
      "phone_code": 41,
      "currency": "CHF",
      "iso_code": "CH",
    },
    {
      "id": 197,
      "name": "Syria",
      "phone_code": 963,
      "currency": "SYP",
      "iso_code": "SY",
    },
    {
      "id": 198,
      "name": "Taiwan",
      "phone_code": 886,
      "currency": "TWD",
      "iso_code": "TW",
    },
    {
      "id": 199,
      "name": "Tajikistan",
      "phone_code": 992,
      "currency": "USD",
      "iso_code": "TJ",
    },
    {
      "id": 200,
      "name": "Tanzania",
      "phone_code": 255,
      "currency": "TZS",
      "iso_code": "TZ",
    },
    {
      "id": 201,
      "name": "Thailand",
      "phone_code": 66,
      "currency": "THB",
      "iso_code": "TH",
    },
    {
      "id": 202,
      "name": "Timor-Leste",
      "phone_code": 670,
      "currency": "USD",
      "iso_code": "TL",
    },
    {
      "id": 203,
      "name": "Togo",
      "phone_code": 228,
      "currency": "XOF",
      "iso_code": "TG",
    },
    {
      "id": 204,
      "name": "Tokelau",
      "phone_code": 690,
      "currency": "NZD",
      "iso_code": "TK",
    },
    {
      "id": 205,
      "name": "Tonga",
      "phone_code": 676,
      "currency": "TOP",
      "iso_code": "TO",
    },
    {
      "id": 206,
      "name": "Trinidad and Tobago",
      "phone_code": 1,
      "currency": "TTD",
      "iso_code": "TT",
    },
    {
      "id": 207,
      "name": "Tunisia",
      "phone_code": 216,
      "currency": "TND",
      "iso_code": "TN",
    },
    {
      "id": 208,
      "name": "Turkey",
      "phone_code": 90,
      "currency": "TRY",
      "iso_code": "TR",
    },
    {
      "id": 209,
      "name": "Turkmenistan",
      "phone_code": 993,
      "currency": "TMT",
      "iso_code": "TM",
    },
    {
      "id": 210,
      "name": "Turks and Caicos Islands",
      "phone_code": 1,
      "currency": "USD",
      "iso_code": "TC",
    },
    {
      "id": 211,
      "name": "Tuvalu",
      "phone_code": 688,
      "currency": "AUD",
      "iso_code": "TV",
    },
    {
      "id": 212,
      "name": "Uganda",
      "phone_code": 256,
      "currency": "UGX",
      "iso_code": "UG",
    },
    {
      "id": 213,
      "name": "Ukraine",
      "phone_code": 380,
      "currency": "UAH",
      "iso_code": "UA",
    },
    {
      "id": 214,
      "name": "United Arab Emirates",
      "phone_code": 971,
      "currency": "AED",
      "iso_code": "AE",
    },
    {
      "id": 215,
      "name": "United Kingdom",
      "phone_code": 44,
      "currency": "GBP",
      "iso_code": "GB",
    },
    {
      "id": 216,
      "name": "United States",
      "phone_code": 1,
      "currency": "USD",
      "iso_code": "US",
    },
    {
      "id": 217,
      "name": "Uruguay",
      "phone_code": 598,
      "currency": "UYU",
      "iso_code": "UY",
    },
    {
      "id": 218,
      "name": "Uzbekistan",
      "phone_code": 998,
      "currency": "UZS",
      "iso_code": "UZ",
    },
    {
      "id": 219,
      "name": "Vanuatu",
      "phone_code": 678,
      "currency": "VUV",
      "iso_code": "VU",
    },
    {
      "id": 220,
      "name": "Venezuela",
      "phone_code": 58,
      "currency": "VEF",
      "iso_code": "VE",
    },
    {
      "id": 221,
      "name": "Vietnam",
      "phone_code": 84,
      "currency": "VND",
      "iso_code": "VN",
    },
    {
      "id": 222,
      "name": "Virgin Islands",
      "phone_code": 1,
      "currency": "USD",
      "iso_code": "VI",
    },
    {
      "id": 223,
      "name": "Wallis and Futuna",
      "phone_code": 681,
      "currency": "USD",
      "iso_code": "WF",
    },
    {
      "id": 224,
      "name": "Yemen",
      "phone_code": 967,
      "currency": "YER",
      "iso_code": "YE",
    },
    {
      "id": 225,
      "name": "Zambia",
      "phone_code": 260,
      "currency": "ZMW",
      "iso_code": "ZM",
    },
    {
      "id": 226,
      "name": "Zimbabwe",
      "phone_code": 263,
      "currency": "USD",
      "iso_code": "ZW",
    }
  ];
}
