name: colgate
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.5+4

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  get: ^4.1.4
  # Splash screen
  flutter_native_splash: ^1.1.8+4
  # Svg assets
  flutter_svg: ^0.22.0
  # For Firebase, Notications & social login
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  google_sign_in: ^4.5.9
  flutter_facebook_login: ^3.0.0
  sign_in_with_apple: ^3.0.0
  # For permenent storage
  flutter_secure_storage: ^4.2.0
  # For getx storage
  get_storage: ^2.0.2
  # For toast message alerts
  fluttertoast: ^7.1.1
  # For check network connectivity
  data_connection_checker: ^0.3.4
  # For http requests
  http: ^0.13.3
  #flutter webview
  webview_flutter: ^2.0.8
  carousel_slider: ^3.0.0
  flutter_markdown: ^0.6.2
  #shimmer effect
  shimmer: ^2.0.0
  # oauth2_client: ^2.2.2
  twilio_flutter: ^0.0.9
  ## Image Pick from camera
  image_picker: ^0.7.5
  dio: ^4.0.0
  image_cropper: ^1.4.0
  flt_telephony_info: any
  sendgrid_mailer: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  # example:
  fonts:
    - family: AGBookPro
      fonts:
        - asset: assets/fonts/AGBookPro/AGBookProMed.otf
        - asset: assets/fonts/AGBookPro/AGBookProMedIta.otf
        - asset: assets/fonts/AGBookPro/AGBookProReg.otf

    - family: Touche
      fonts:
        - asset: assets/fonts/Touche/touche-1.ttf
        - asset: assets/fonts/Touche/touche-2.ttf
        - asset: assets/fonts/Touche/touche-3.ttf
        - asset: assets/fonts/Touche/touche-4.ttf
        # - asset: assets/fonts/AGBookPro/AGBookPro-ExtraBoldItalic.otf
        # - asset: assets/fonts/AGBookPro/AGBookPro-ExtraLight.otf
        # - asset: assets/fonts/AGBookPro/AGBookPro-Light.otf
        # - asset: assets/fonts/AGBookPro/AGBookPro-Medium.otf
        # - asset: assets/fonts/AGBookPro/AGBookPro-Regular.otf
        # - asset: assets/fonts/AGBookPro/AGBookPro-SemiBold.otf
        # - asset: assets/fonts/AGBookPro/AGBookPro-Thin.otf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.otf
  #       - asset: fonts/Schyler-Italic.otf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.otf
  #       - asset: fonts/TrajanPro_Bold.otf
  #         weight: 700
  #
